### ISSUE TITLE
Добавить в раздел про разметку сервисы и плагины для генерации картинок разного размера например placeholdit и подобные

### ISSUE THREAD

**Issue by tsergeytovarov** [tsergeytovarov/htmlacademy-basic-additional-material#12]

**Comment by aalexeev239** [comment]
http://placekitten.com/
http://placeboobs.com/ 

А если серьезно, мне нравится сниппет в саблайм https://packagecontrol.io/packages/FakeImg%20Image%20Placeholder%20Snippet
вставить картинку этим способом - быстрее всего
