### ISSUE TITLE
Перенести в репозиторий статью по селекторам и отредактировать ее

### ISSUE THREAD

**Issue by tsergeytovarov** [tsergeytovarov/htmlacademy-basic-additional-material#19]
http://ourworkspace.ru/htmlacademy/blog/talk-about-css-selcetors/

есть ли в ней смысл или заменить чем то уже готовым

**Comment by mityamf** [comment]
смысл есть, я вообще себе отдельно записал все виды селекторов )))

**Comment by elemeNtk0** [comment]
@mityamf  Может дополнишь своим списком? :)

**Comment by mityamf** [comment]
@elemeNtk0 ну в списке не хватает соседних селекторов, например. (li+li)
я так я вообще ещё только учусь, я же за вами записываю ))))

**Comment by elemeNtk0** [comment]
Ну я же не знал =)
Тогда надо что-то поискать и переработать

**Comment by tsergeytovarov** [comment]
Значит статью доработаем)

**Comment by aalexeev239** [comment]
@tsergeytovarov ссылка не открывается, но совершенно забыл про две отличные статьи
30 CSS селекторов, которые вы должны запомнить
http://code.tutsplus.com/ru/tutorials/the-30-css-selectors-you-must-memorize--net-16048
Аксиоматический CSS и лоботомированные совы _(уровень выше базового)_
http://frontender.info/axiomatic-css-and-lobotomized-owls/#aksiomaticheskiycssilobotomirovannesov
